### ISSUE TITLE
`ul` button, `li` er omheen

### ISSUE THREAD

**Issue by Lmikkers** [ArmanVD/the-client-website#1]
Je hebt een lijst met list items en daarin heb je een button, deze moet nog in een `<li>` komen, omdat dit ook een list item is.

https://github.com/ArmanVD/the-client-website/blob/06f077374e80f4879c0da7c6dde2dcaa4ae7002a/index.html#L13-L23

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

**Comment by ArmanVD** [comment]
Heb ik aangepast
